ROR format
UKGovLD/registry-core pull request #132
Opened 2020-11-24 13:59 UTC by simonoakesepimorphics

Support ROR description of registry and registers.
[Wiki](https://github.com/UKGovLD/registry-core/wiki/WIP-ROR-Format-Preview)

2020-11-25 09:33 UTC, der requested changes
The projection machinery makes for very neat code, cunning. Though I would have appreciated some comments somewhere e.g. `ModelProjectBuilder` to explain the concept a bit.

More seriously the tests fail for me with NPR errors, see comment on `RequestProcessor`.

2020-11-25 09:33 UTC, der commented on src/test/java/com/epimorphics/registry/webapi/RdfXmlRorMarshallerTest.java
> +        assertEquals(expected, result);
There is a risk that the ordering of the RDF/XML is not stable thanks to the use of HashMaps internally to jena. In particular the ordering of the different properties tags within a resource tag could change which would would break the test. Could deal with that if it comes up. I've sometimes previously do a a mix of check that key expected lines are included in the output stream (without regard to order) and re-parsing the output so as to be able to a model isomorphism test.

2020-11-25 09:33 UTC, der commented on src/main/java/com/epimorphics/registry/webapi/RequestProcessor.java
> +        } else if (mediaType.equals(RdfXmlRorMarshaller.MIME_TYPE) && path.isEmpty()) {
This relies on mediaType being non-null. For me all the integration tests fail with NPRs at this point thanks to the line:

    return doRead(result, null);

in `RequestProcessor.read`

2020-11-26 13:18 UTC, simonoakesepimorphics commented on src/main/java/com/epimorphics/registry/webapi/RequestProcessor.java
> +        } else if (mediaType.equals(RdfXmlRorMarshaller.MIME_TYPE) && path.isEmpty()) {
I've added a null check.

2020-12-07 17:33 UTC, der approved these changes
Looks good, thanks.

2020-12-08 11:14 UTC, merged